// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1h_B_RXJBrmS7q_BVZ8dQFUXetYTz8rk',
    appId: '1:1074968909224:android:49b10295465012462b799d',
    messagingSenderId: '1074968909224',
    projectId: 'bloc-fb-auth',
    storageBucket: 'bloc-fb-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd1MTlkH7Vh9H6G6QIXLQOgzQSjxSBB6E',
    appId: '1:1074968909224:ios:5704cc7cdbc7000e2b799d',
    messagingSenderId: '1074968909224',
    projectId: 'bloc-fb-auth',
    storageBucket: 'bloc-fb-auth.appspot.com',
    androidClientId: '1074968909224-jbk5isu5qs0mee645of7fpkh6k4mepno.apps.googleusercontent.com',
    iosClientId: '1074968909224-qt0lgj9jbcvjhff91eueo8g19ojt22bo.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocFbAuth',
  );
}
